#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../.." && pwd)

T_END_S=${1:-70}

OS_NAME=$(uname)
LIB_EXT="dylib"
if [[ "${OS_NAME}" == "Linux" ]]; then
  LIB_EXT="so"
fi

LIB_PATH_DEFAULT="${REPO_ROOT}/build/px4_sitl_lockstep/src/lib/px4_lockstep/libpx4_lockstep.${LIB_EXT}"
MISSION_DEFAULT="${REPO_ROOT}/Tools/px4_lockstep_julia/examples/simple_mission.waypoints"
DEPOT_DEFAULT="${REPO_ROOT}/Tools/px4_lockstep_julia/.julia_depot"

PX4_LOCKSTEP_LIB=${PX4_LOCKSTEP_LIB:-${LIB_PATH_DEFAULT}}
PX4_LOCKSTEP_MISSION=${PX4_LOCKSTEP_MISSION:-${MISSION_DEFAULT}}
JULIA_DEPOT_PATH=${JULIA_DEPOT_PATH:-${DEPOT_DEFAULT}}

: "${PX4_LOCKSTEP_UORB_BATTERY:=1}"
: "${PX4_LOCKSTEP_UORB_ATTITUDE:=1}"
: "${PX4_LOCKSTEP_UORB_LOCAL_POSITION:=1}"
: "${PX4_LOCKSTEP_UORB_GLOBAL_POSITION:=1}"
: "${PX4_LOCKSTEP_UORB_RATES:=1}"
: "${PX4_LOCKSTEP_UORB_LAND_DETECTED:=1}"
: "${PX4_LOCKSTEP_UORB_VEHICLE_STATUS:=1}"
: "${PX4_LOCKSTEP_UORB_VEHICLE_CONTROL_MODE:=1}"
: "${PX4_LOCKSTEP_UORB_ACTUATOR_ARMED:=1}"
: "${PX4_LOCKSTEP_UORB_HOME_POSITION:=1}"
: "${PX4_LOCKSTEP_UORB_GEOFENCE_STATUS:=1}"

IRIS_T_END_S=${T_END_S} \
PX4_LOCKSTEP_LIB=${PX4_LOCKSTEP_LIB} \
PX4_LOCKSTEP_MISSION=${PX4_LOCKSTEP_MISSION} \
PX4_LOCKSTEP_UORB_BATTERY=${PX4_LOCKSTEP_UORB_BATTERY} \
PX4_LOCKSTEP_UORB_ATTITUDE=${PX4_LOCKSTEP_UORB_ATTITUDE} \
PX4_LOCKSTEP_UORB_LOCAL_POSITION=${PX4_LOCKSTEP_UORB_LOCAL_POSITION} \
PX4_LOCKSTEP_UORB_GLOBAL_POSITION=${PX4_LOCKSTEP_UORB_GLOBAL_POSITION} \
PX4_LOCKSTEP_UORB_RATES=${PX4_LOCKSTEP_UORB_RATES} \
PX4_LOCKSTEP_UORB_LAND_DETECTED=${PX4_LOCKSTEP_UORB_LAND_DETECTED} \
PX4_LOCKSTEP_UORB_VEHICLE_STATUS=${PX4_LOCKSTEP_UORB_VEHICLE_STATUS} \
PX4_LOCKSTEP_UORB_VEHICLE_CONTROL_MODE=${PX4_LOCKSTEP_UORB_VEHICLE_CONTROL_MODE} \
PX4_LOCKSTEP_UORB_ACTUATOR_ARMED=${PX4_LOCKSTEP_UORB_ACTUATOR_ARMED} \
PX4_LOCKSTEP_UORB_HOME_POSITION=${PX4_LOCKSTEP_UORB_HOME_POSITION} \
PX4_LOCKSTEP_UORB_GEOFENCE_STATUS=${PX4_LOCKSTEP_UORB_GEOFENCE_STATUS} \
JULIA_DEPOT_PATH=${JULIA_DEPOT_PATH} \
julia --project="${REPO_ROOT}/Tools/px4_lockstep_julia" \
  -e 'using PX4Lockstep.Sim; Sim.simulate_iris_mission(mode=:live, log_sinks=Sim.Logging.CSVLogSink("sim_log.csv"))'
